version: '3.8'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: crud_srpingboot
    ports:
        - 3306:3306

  app:
    build: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    depends_on:
        - db
volumes:
    db_data: